name: Python Tests

on: [push, pull_request]  # Trigger CI on push and pull requests

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu for testing
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code

    - name: Set up Python
      uses: actions/setup-python@v2  # Setup Python for the environment
      with:
        python-version: '3.x'  # Use Python 3.x
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Install pytest
    
    - name: Run tests
      run: |
        pytest test_functions.py  # Run the tests
